---
title: "qPCR Trial 2 Results PaV1 eDNA Detection"
author: "Aiko Abo Dominguez"
date: "2025-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Install packages
```{r}
#install.packages("ggpmisc")

library(tidyr)
library(dplyr)
library(ggplot2)
library(ggpmisc)
library(tidyverse)
library(purrr)
library(RColorBrewer)
```

Load CT files
```{r}
setwd("/Users/aiko.abo.dominguez/Desktop/PaV1eDNA_detection")
getwd()

CTs <- read.csv("/Users/aiko.abo.dominguez/Desktop/PaV1eDNA_detection/07302025_qPCR_Trial2_PAV1_eDNADetection.csv")
concentrations <- read.csv("/Users/aiko.abo.dominguez/Desktop/PaV1eDNA_detection/07302025_dilution_concentrations_PAV1_eDNADetection.csv")

#check they uploaded correctly and make sure numeric
head(CTs)
CTs$CT <- as.numeric(CTs$CT) #this changes "undetermined" to NA
str(CTs)
```


Organize data
```{r}
#add concentrations to CTs
# Create column in CTs for matching (2nd character from Sample.Name)
CTs <- CTs %>%
  mutate(
    dilution = substr(Sample.Name, 2, 2)
  )

#Create label for dilution #
concentrations <- concentrations %>%
  mutate(dilution = ifelse(nchar(Sample.Name) >= 2, substr(Sample.Name, 2, 2), Sample.Name))
concentrations

#Make simplified DF
CTs_clean <- CTs %>%
  select(dilution,Sample.Name,CT,Ct.Mean,Ct.SD) %>%
  left_join(concentrations %>% select(dilution, Quantity), by = "dilution") %>%
  mutate(group=substr(Sample.Name,1,1),
         logCT=log(CT)) %>%
  mutate(group_name = ifelse(group=="S",
                             "Sterivex",
                             ifelse(group=="B","Beaker",
                                    ifelse(group=="F","Filtrate",
                                           ifelse(group=="P","Positive Control",
                                                  ifelse(group=="N","NTC",
                                                         ifelse(group=="E","Extraction Blank",NA)))))))

#View(CTs_clean)
str(CTs_clean)
```

Calculate means of blanks, NTCs, positive controls
```{r}
extraction_blank <- mean(CTs_clean$CT[CTs_clean$group=="E"],na.rm = TRUE)
NTC <- mean(CTs_clean$CT[CTs_clean$group=="N"],na.rm = TRUE)
positive_ctrl <-mean(CTs_clean$CT[CTs_clean$group=="P"],na.rm = TRUE)
```

Plotting CTs
```{r}
#create color palette
mycolors <- colorRampPalette(c(brewer.pal(9, "Set1"),
                               brewer.pal(3, "Set2")))
#plot CTs log transformted
meanCT_plot <- CTs_clean %>%
  #remove extraction blank, NTC, positive controls
  subset(!(group %in% c("E","N","P"))) %>%
  
  #plot aesthetics
  ggplot(aes(x = Quantity, y = CT, color = group_name)) +
  geom_point(show.legend=TRUE) +
  scale_color_manual(values=mycolors(3)) +
  scale_x_continuous(trans='log10') +
  xlab("Log(Concentration of serum)") +
  ylab("Cycle threshold") +
  ylim(0,NA)+
  theme_bw()+
  
  #add lines with extraction blank, NTC, positive controls
  geom_hline(yintercept=extraction_blank,color=mycolors(1)) +
  annotate("text",x=.001,y=extraction_blank+extraction_blank*.05,label="Extraction blank",size=5) +
  
  geom_hline(yintercept=NTC,color=mycolors(1)) +
  annotate("text",x=.001,y=NTC+NTC*.04,label="NTC",size=5) +
  
  geom_hline(yintercept=positive_ctrl,color=mycolors(1)) +
  annotate("text",x=.001,y=positive_ctrl+positive_ctrl*.1,label="Positive control",size=5) +
  
  #increase font sizes
  theme(
      legend.text = element_text(size = 18),
      legend.title = element_text(size = 18),
      axis.title.x = element_text(size = 24),
      axis.title.y = element_text(size = 24),
      axis.text.x = element_text(size = 20),
      axis.text.y = element_text(size = 20)
    ) 

meanCT_plot

#save plot
ggsave('logCTs_PaV1eDNA_detectionTrial2.png', plot=meanCT_plot,
       width = 11,
       height = 7,
       path = "/Users/aiko.abo.dominguez/Desktop/PaV1eDNA_detection/figures")
```

Plot CTs NOT log transformted
```{r}

meanCT_plot <- CTs_clean %>%
  #remove extraction blank, NTC, positive controls
  subset(!(group %in% c("E","N","P"))) %>%
  
  #plot aesthetics
  ggplot(aes(x = Quantity, y = CT, color = group_name)) +
  geom_point(show.legend=TRUE) +
  scale_color_manual(values=mycolors(3)) +
  xlab("Serum concentration") +
  ylab("Cycle threshold") +
  theme_bw()+
  
  #add lines with extraction blank, NTC, positive controls
  geom_hline(yintercept=extraction_blank,color=mycolors(1)) +
  annotate("text",x=.001,y=extraction_blank+extraction_blank*.05,label="Extraction blank") +
  
  geom_hline(yintercept=NTC,color=mycolors(1)) +
  annotate("text",x=.001,y=NTC+NTC*.04,label="NTC") +
  
  geom_hline(yintercept=positive_ctrl,color=mycolors(1)) +
  annotate("text",x=.001,y=positive_ctrl+positive_ctrl*.1,label="Positive control") +
  
  #change text sizes
  theme(
      legend.text = element_text(size = 18),
      legend.title = element_text(size = 18),
      axis.title.x = element_text(size = 24),
      axis.title.y = element_text(size = 24),
      axis.text.x = element_text(size = 20),
      axis.text.y = element_text(size = 20)
    ) 


meanCT_plot

#save plot
ggsave('CTs_PaV1eDNA_detectionTrial2.png', plot=meanCT_plot,
       width = 11,
       height = 7,
       path = "/Users/aiko.abo.dominguez/Desktop/PaV1eDNA_detection/figures")
```

